### PR TITLE
Migrate to travis-ci from gitlab-ci

### PR DESCRIPTION
**Pull request by CAMOBAP795**
- #8

### CODE REVIEW

**Comment by CAMOBAP795** [comment]
@ronaldtse build because https://raw.githubusercontent.com/metanorma/plantuml-install/master/ubuntu.sh -> 404 

Maybe you can point me where `plantuml-install/master/ubuntu.sh` can be obtained?

**Comment by ronaldtse** [comment]
That script is still in https://github.com/riboseinc/plantuml-install/

**Comment by ronaldtse** [comment]
DOCKER_LOGIN_USERNAME, DOCKER_LOGIN_PASSWORD added to `.travis.yml`

**Comment by CAMOBAP795** [comment]
@ronaldtse thanks, looks like we definitely have problem with `Dockerfile.in`, let me know if I should continue investigate it

**Comment by ronaldtse** [comment]
@CAMOBAP795 the build is running but it looks like it's stuck.

The problem is:
```
> puppeteer@1.13.0 install /root/.nvm/versions/node/v11.12.0/lib/node_modules/puppeteer
> node install.js
mChromium downloaded to /root/.nvm/versions/node/v11.12.0/lib/node_modules/puppeteer/.local-chromium/linux-637110
+ puppeteer@1.13.0
added 43 packages from 22 contributors in 7.571s
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    15  100    15    0     0    174      0 --:--:-- --:--:-- --:--:--   174
bash: line 1: 404:: command not found
The command '/bin/sh -c /tmp/ubuntu.sh' returned a non-zero code: 127
make: *** [build-metanorma] Error 127
rm metanorma/Dockerfile
```

It looks like it can't install puppeteer. Can you please help fix? Thanks!

**Comment by CAMOBAP795** [comment]
> It looks like it can't install puppeteer. Can you please help fix?

Nope, I'm 100% sure that it's not related to `puppeteer` because when I added
```
RUN sed 's,https://raw.githubusercontent.com/metanorma/plantuml-install/master/ubuntu.sh,https://raw.githubusercontent.com/riboseinc/plantuml-install/master/ubuntu.sh,g' /tmp/ubuntu.sh > /tmp/ubuntu.sh
```

This issue gone

Next one was:
```
The command '/bin/bash -l -c which ruby' returned a non-zero code: 1
```

It was solved by `apt-get install -y ruby`

Next one was:
```
Building native extensions. This could take a while...
ERROR:  Error installing sassc:
	ERROR: Failed to build gem native extension.
    current directory: /var/lib/gems/2.5.0/gems/ffi-1.10.0/ext/ffi_c
/usr/bin/ruby2.5 -I /usr/local/lib/site_ruby/2.5.0 -r ./siteconf20190316-217-gcglz0.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h
extconf failed, exit code 1
Gem files will remain installed in /var/lib/gems/2.5.0/gems/ffi-1.10.0 for inspection.
Results logged to /var/lib/gems/2.5.0/extensions/x86_64-linux/2.5.0/ffi-1.10.0/gem_make.out
The command '/bin/bash -l -c rvm use ${RUBY_VER};   gem update --system;   gem install bundler   && gem install rake   && gem install sassc   && bundle' returned a non-zero code: 1
```

I'm not sure that I will fix it today but tomorrow definitely

**Comment by ronaldtse** [comment]
I see. Then can you also fix up https://raw.githubusercontent.com/riboseinc/metanorma-linux-setup/master/ubuntu.sh so it points to the correct "plantuml-setup" script? Thanks.

**Comment by CAMOBAP795** [comment]
@ronaldtse sure let me just find all pieces to make it work after it I will prepare PRs to right repositories (of course I will not leave this `sed` command above in `Dockerfile.in`)

**Comment by ronaldtse** [comment]
@CAMOBAP795 good to know 👍 😉

**Comment by CAMOBAP795** [comment]
It's green now, but I need to understand why `apt-get install` from https://raw.githubusercontent.com/riboseinc/metanorma-linux-setup/master/ubuntu.sh doesn't work because when I added `ruby  libffi-dev ruby-dev libffi-dev libxml2-dev libxslt-dev` to `Dockerfile.in` it works

Investigation will be continued tomorrow

**Comment by CAMOBAP795** [comment]
Hi @ronaldtse @opoudjis 

Let me summarize what we have for now:
 - Travis CI ready and works (green)
 - I have removed `RUN` for `ubuntu.sh` from `Dockerfile` because the don't affect result image + it duplicate logic in `Dockerfile` below (i.e. pupeteer installation)
 - To make run work as expected it need to be not `RUN xxx.sh` but `RUN curl -L xxx.sh | bash -s`
 - According best practices https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#run `apt-get` should be called explicitly

Next steps:
 - PR is ready for review feel free to criticize it

Open Questions:
 - Which approach we will follow?
    1. Everything inside Dockerfile OR
    2. Docker-file download scripts & run it to install dependencies
 - Why do we need RVM inside docker?

**Comment by ronaldtse** [comment]
We need a separate Linux install script because we have to install the full chain on Travis every time. The docker container should use the same script that installs for Ubuntu.

**Comment by CAMOBAP795** [comment]
@ronaldtse thanks for explanation, may I ask you to explain idea behind 2cd46a5534efba7b928a7aec2701a84814f74ef9, especially:
 - why we need rvm there
 - and why `gem-install` was commented

**Comment by ronaldtse** [comment]
@CAMOBAP795 sure.

> why we need rvm there

We needed to lock to a version of Ruby -- previously, Metanorma was not compatible with 2.5 and then 2.6. We will still need to lock the Ruby version because the version supplied by Ubuntu isn't always the one we want.

> and why gem-install was commented

Because we now use a `Gemfile` and use `bundle` for installing gems. That's why `gem-install.sh` is no longer needed.

Moreover, sometimes we need this to override the gem releases with the git versions for the Docker container (think hot-fixes).

**Comment by CAMOBAP795** [comment]
@ronaldtse thanks for answers let me update this PR according new info

**Comment by CAMOBAP795** [comment]
PR will be updated once https://github.com/metanorma/metanorma-linux-setup/pull/4 will be merged

**Comment by CAMOBAP795** [comment]
@ronaldtse ready for review & merge

**Pull request merged**
