### PR TITLE
#133 Upgrade ruby version to 3.1

### PR DESCRIPTION
**Pull request by CAMOBAP**
- #133

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP the builds are failing on compilation of the “rice” gem at version 3.0.0. However, we should have already upgraded it to 4.0.0 for expressir. Can you help check? Thanks.

**Comment by ronaldtse** [comment]
Thank you @CAMOBAP !

**Comment by ronaldtse** [comment]
BTW will the merging of this one trigger metanorma-docker-private?

**Comment by CAMOBAP** [comment]
> BTW will the merging of this one trigger metanorma-docker-private?

Not yet unfortunately I think how to simplify maintenance of them

Probably I will move nist image back to this repo, I still think how to make it simplier

**Comment by ronaldtse** [comment]
But can we have private container in a public repo? Or they are separate?

**Comment by CAMOBAP** [comment]
> But can we have a private container in a public repo? Or they are separate?

As far as I understand yes, according to the documentation: during the first push, the package "inherit" visibility from the repository, so now we can do the push from other place

**Comment by ronaldtse** [comment]
I see. I do remember that on GH Docker containers have a separate access control page, so maybe we don’t need a separate repository. However, we may not want the public to see even the names of the private containers.

**Comment by CAMOBAP** [comment]
> I see. I do remember that on GH Docker containers have a separate access control page, so maybe we don’t need a separate repository. However, we may not want the public to see even the names of the private containers.

Good point

In this case, I will update `metanorma-docker-private` to maximally reuse code from `metanorma-docker` (Dockerfiles, scripts), and we will keep there any further private images

I will do this in the scope of:
 - https://github.com/metanorma/metanorma-docker/issues/134
 - https://github.com/metanorma/metanorma-docker-private/issues/1

**Comment by ronaldtse** [comment]
Thank you @CAMOBAP !

**Pull request merged**
