### PR TITLE
Add description of push process by CI

### PR DESCRIPTION
**Pull request by CAMOBAP795**
- https://github.com/metanorma/metanorma-docker/issues/13#issuecomment-479753956

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP795 I think we also want to tag the Metanorma containers with the same version (as the git tag version). Can you help update it?

**Comment by CAMOBAP795** [comment]
@ronaldtse BTW how we manage ruby gem versions here? I didn't see any restrictions in Gemfile in `metanorma` or `mn` directories

**Comment by ronaldtse** [comment]
There's a `Gemfile.lock` in `metanorma/`.

**Comment by CAMOBAP795** [comment]
@ronaldtse ready to merge, could you please review

**Comment by ronaldtse** [comment]
Merging now, @CAMOBAP795 can you ensure #14 will work? Thanks.

**Pull request merged**
