### PR TITLE
Move yuichielectric/dive-action to separate job

### PR DESCRIPTION
**Pull request by CAMOBAP**
- #147 

### What's done (alpine)

 - OpenJDK downgrade to 8: -100MB
 - Uninstall gcc/g++: -~200MB
 - Remove test files from gems: ~100MB

Potential:
 - Inkscape takes ~200Mb, this direction can be investigated, probably we can rebuild inkscape to keep it minimal
 - python with packages takes ~170Mb, also looks too big

### CODE REVIEW

**Review by ronaldtse — APPROVED** [review]

**Comment by CAMOBAP** [comment]
For ubuntu and ruby images size wasn't decreased that much, still investigating

**Comment by CAMOBAP** [comment]
Done:
 - alpine now less than 1GB
 - ruby and ubuntu ones are less than 1.4GB

**Comment by ronaldtse** [comment]
Thank you @CAMOBAP ! Can you also add this size information to the README so we remember this? Thanks!

**Comment by CAMOBAP** [comment]
@ronaldtse maybe badges will be better?

[metanorma:alpine](https://hub.docker.com/r/metanorma/metanorma/)
[metanorma:ubuntu](https://hub.docker.com/r/metanorma/metanorma/)
[metanorma:ruby](https://hub.docker.com/r/metanorma/metanorma/)

**Pull request merged**
