### PR TITLE
#80 add ietf to test pool

### PR DESCRIPTION
**Pull request by CAMOBAP**
- #80

### CODE REVIEW

**Comment by CAMOBAP** [comment]
@ronaldtse iho is broken should be exclude it or wait for fix

**Comment by ronaldtse** [comment]
@CAMOBAP ready to merge?

**Comment by CAMOBAP** [comment]
@ronaldtse formal, yes, in fact, if we will merge this it will turn our release process to hell. All because of an annoying network timeout issue. I am just wondering, can we mirror workgroup somehow to make it more stable?

As far as I understand we just get XML resources from https://tools.ietf.org/wg/..., why we cannot implement some crawler which will push all required resources to github repo, we can even do this with github action, I just need to know what should we grab from https://tools.ietf.org and what is the appropriate format to store it

**Comment by ronaldtse** [comment]
> As far as I understand we just get XML resources from https://tools.ietf.org/wg/..., why we cannot implement some crawler which will push all required resources to github repo, we can even do this with github action, I just need to know what should we grab from https://tools.ietf.org and what is the appropriate format to store it

I agree. Let's make a "relaton-ietf-wg" that mirrors the data we need from tools.ietf.org in a structure that we desire.

**Comment by CAMOBAP** [comment]
Closed as outdated

**Pull request closed without merging**
