### PR TITLE
#86 trigger samples repos on push to master

### PR DESCRIPTION
**Pull request by CAMOBAP**
- #86

### CODE REVIEW

**Comment by CAMOBAP** [comment]
Waiting for merge samples

**Comment by CAMOBAP** [comment]
@ronaldtse @opoudjis I need your opinion is that ok that we will trigger mn-samples on each push to master (to me it sounds reasonable because we update `mn` image on each master push)

**Comment by ronaldtse** [comment]
@CAMOBAP yes it makes sense (but please only trigger the docker workflow in mn-{samples,templates}-*)

**Comment by CAMOBAP** [comment]
@ronaldtse yep exactly we trigger the ONLY docker workflow, also, for now, we don't have docker flow for mn-templates-*, should we add it?

**Comment by ronaldtse** [comment]
> we don't have docker flow for mn-templates-*, should we add it?

Yes please, thanks!

**Pull request merged**
