### PR TITLE
#66 run test on all samples

### PR DESCRIPTION
**Pull request by CAMOBAP**

### CODE REVIEW

**Comment by CAMOBAP** [comment]
@ronaldtse @abunashir I propose to exclude `ietf` & `mpfa` from the testing set because of known issues:
 - https://github.com/metanorma/mn-samples-ietf/issues/14
 - https://github.com/metanorma/metanorma-docker/issues/77

**Comment by ronaldtse** [comment]
@CAMOBAP 
1. We do not need to generate PDF for IETF for now. Let's remove PDF output from IETF. (from `mn-output-extensions`)
2. Let's exclude mpfd for now.

**Comment by CAMOBAP** [comment]
@ronaldtse I have updated https://github.com/metanorma/mn-samples-ietf/issues/14
I propose to exclude it temporarily

**Comment by ronaldtse** [comment]
@CAMOBAP agree, let's do it.

**Pull request merged**
