### PR TITLE
Add documentation for docker hub

### PR DESCRIPTION
**Pull request by abunashir**
This commit adds a basic documentation that we can manually add to docker hub, so whenever a user is browsing our image then then they will have a clear overview of this image.

### CODE REVIEW

**Comment by ronaldtse** [comment]
Can we split the "Usages" into multiple subsections?

In addition:

1. Add Windows usage instructions (@CAMOBAP795 can help?)
2. How to update the image
3. How to use a specific version of the image

Thanks!

**Comment by abunashir** [comment]
@ronaldtse: I've updated the image, could you please check and we might also need to adjust some phrasing :heart:

**Comment by opoudjis** [comment]
I'm keeping away from this gem, but @ronaldtse @strogonoff, shouldn't this documentation be integrated with metanorma.com?

**Comment by abunashir** [comment]
@opoudjis Personally, I would prefer to keep this one with the repo, since its a docker image, and having a document here will allow us to manage a draft before we actually change our actual documentation in docker hub. But it's your call, I will leave this up to you and @ronaldtse.

**Comment by ronaldtse** [comment]
> I'm keeping away from this gem, but @ronaldtse @strogonoff, shouldn't this documentation be integrated with metanorma.com?

> Personally, I would prefer to keep this one with the repo, since its a docker image, and having a document here will allow us to manage a draft before we actually change our actual documentation in docker hub.

Perhaps @strogonoff could let us know how we can best manage docker image documentation. I agree that the usage documentation of the docker container should be separated into "draft" and "official", and that the "official" one should be kept in metanorma.com.

**Comment by ronaldtse** [comment]
@abunashir can you help post the resulting documentation on Docker Hub? Thanks!

**Pull request merged**
