### PR TITLE
#21 Update metanorma version to 1.2.2

### PR DESCRIPTION
**Pull request by CAMOBAP795**
- #21 

@ronaldtse  Once CI passed I will merge & tag it

### CODE REVIEW

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP795 !

**Comment by CAMOBAP795** [comment]
push to docker hub on the way https://travis-ci.com/metanorma/metanorma-docker/builds/119292570

**Comment by CAMOBAP795** [comment]
@ronaldtse done https://hub.docker.com/r/metanorma/metanorma/tags

**Comment by ronaldtse** [comment]
Thanks?

**Pull request merged**
