### PR TITLE
#134 #123 update workflow to use docker/build-and-push

### PR DESCRIPTION
**Pull request by CAMOBAP**
- refactor workflow to avoid envsubst
 - publish to ghrc.io

#### Issues
 - #134 
 - #123

### CODE REVIEW

**Comment by ronaldtse** [comment]
Interesting failure in linux/arm64 build, also due to emf2svg.

```
#14 4824.4 Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
#14 4824.4 
#14 4824.4     current directory: /usr/local/bundle/gems/emf2svg-1.0.0/ext
#14 4824.4 /usr/local/bin/ruby -I /usr/local/lib/ruby/3.1.0 -r
#14 4824.4 ./siteconf20220315-7-t765el.rb extconf.rb
#14 4824.4 
Downloading libemf2svg.tar.gz (  0%) 
#14 4824.4 Extracting libemf2svg.tar.gz into /tmp/d20220315-13261-vfombp... DEBUG: env is
#14 4824.4 {}
#14 4824.4 DEBUG: command is ["tar", "zxf",
#14 4824.4 "/usr/local/bundle/gems/emf2svg-1.0.0/ports/archives/libemf2svg.tar.gz", "-C",
#14 4824.4 "/tmp/d20220315-13261-vfombp"]
#14 4824.4 DEBUG: options are {[:out, :err]=>["/tmp/d20220315-13261-vfombp/extract.log",
#14 4824.4 "a"]}
#14 4824.4 OK
#14 4824.4 DEBUG: env is {}
#14 4824.4 DEBUG: command is ["cmake", "-DCMAKE_BUILD_TYPE=Release",
#14 4824.4 "-DCMAKE_INSTALL_PREFIX=/usr/local/bundle/gems/emf2svg-1.0.0/ext/port", "."]
#14 4824.4 Running 'configure' for libemf2svg 1.3.0... DEBUG: options are {[:out,
#14 4824.4 :err]=>["/tmp/d20220315-13261-vfombp/configure.log", "a"]}
#14 4824.4 /usr/local/bundle/gems/mini_portile2-2.6.1/lib/mini_portile2/mini_portile.rb:418:in
#14 4824.4 `spawn': No such file or directory - cmake (Errno::ENOENT)
#14 4824.4 from
#14 4824.4 /usr/local/bundle/gems/mini_portile2-2.6.1/lib/mini_portile2/mini_portile.rb:418:in
#14 4824.4 `block in execute'
#14 4824.4 from
#14 4824.4 /usr/local/bundle/gems/mini_portile2-2.6.1/lib/mini_portile2/mini_portile.rb:409:in
#14 4824.4 `chdir'
#14 4824.4 from
#14 4824.4 /usr/local/bundle/gems/mini_portile2-2.6.1/lib/mini_portile2/mini_portile.rb:409:in
#14 4824.4 `execute'
#14 4824.4 	from /usr/local/bundle/gems/emf2svg-1.0.0/lib/emf2svg/recipe.rb:68:in `execute'
#14 4824.4 from
#14 4824.4 /usr/local/bundle/gems/mini_portile2-2.6.1/lib/mini_portile2/mini_portile_cmake.rb:24:in
#14 4824.4 `configure'
#14 4824.4 from
#14 4824.4 /usr/local/bundle/gems/mini_portile2-2.6.1/lib/mini_portile2/mini_portile.rb:179:in
#14 4824.4 `cook'
#14 4824.4 	from /usr/local/bundle/gems/emf2svg-1.0.0/lib/emf2svg/recipe.rb:26:in `cook'
#14 4824.4 	from extconf.rb:6:in `<main>'
#14 4824.4 
#14 4824.4 extconf failed, exit code 1
#14 4824.4 
#14 4824.4 Gem files will remain installed in /usr/local/bundle/gems/emf2svg-1.0.0 for
#14 4824.4 inspection.
#14 4824.4 Results logged to
#14 4824.4 /usr/local/bundle/extensions/aarch64-linux/3.1.0/emf2svg-1.0.0/gem_make.out
#14 4824.4 
#14 4824.4   /usr/local/lib/ruby/3.1.0/rubygems/ext/builder.rb:95:in `run'
#14 4824.4 /usr/local/lib/ruby/3.1.0/rubygems/ext/ext_conf_builder.rb:47:in `block in
#14 4824.4 build'
#14 4824.4   /usr/local/lib/ruby/3.1.0/tempfile.rb:317:in `open'
#14 4824.4   /usr/local/lib/ruby/3.1.0/rubygems/ext/ext_conf_builder.rb:26:in `build'
#14 4824.4   /usr/local/lib/ruby/3.1.0/rubygems/ext/builder.rb:161:in `build_extension'
#14 4824.4 /usr/local/lib/ruby/3.1.0/rubygems/ext/builder.rb:195:in `block in
#14 4824.4 build_extensions'
#14 4824.4   /usr/local/lib/ruby/3.1.0/rubygems/ext/builder.rb:192:in `each'
#14 4824.4   /usr/local/lib/ruby/3.1.0/rubygems/ext/builder.rb:192:in `build_extensions'
#14 4824.4   /usr/local/lib/ruby/3.1.0/rubygems/installer.rb:853:in `build_extensions'
#14 4824.4 /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/rubygems_gem_installer.rb:71:in
#14 4824.4 `build_extensions'
#14 4824.4 /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/rubygems_gem_installer.rb:28:in
#14 4824.4 `install'
#14 4824.4 /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/source/rubygems.rb:204:in
#14 4824.4 `install'
#14 4824.4 /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/installer/gem_installer.rb:54:in
#14 4824.4 `install'
#14 4824.4 /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/installer/gem_installer.rb:16:in
#14 4824.4 `install_from_spec'
#14 4824.4 /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/installer/parallel_installer.rb:186:in
#14 4824.4 `do_install'
#14 4824.4 /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/installer/parallel_installer.rb:177:in
#14 4824.4 `block in worker_pool'
#14 4824.4   /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/worker.rb:62:in `apply_func'
#14 4824.4 /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/worker.rb:57:in `block in
#14 4824.4 process_queue'
#14 4824.4   /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/worker.rb:54:in `loop'
#14 4824.4 /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/worker.rb:54:in
#14 4824.4 `process_queue'
#14 4824.4 /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/worker.rb:91:in `block (2
#14 4824.4 levels) in create_threads'
#14 4824.4 
#14 4824.4 An error occurred while installing emf2svg (1.0.0), and Bundler cannot continue.
#14 4824.4 
#14 4824.4 In Gemfile:
#14 4824.4   metanorma-cli was resolved to 1.5.11, which depends on
#14 4824.4     metanorma-bipm was resolved to 2.0.5, which depends on
#14 4824.4       metanorma-generic was resolved to 2.0.3, which depends on
#14 4824.4         metanorma-standoc was resolved to 2.0.4, which depends on
#14 4824.4           metanorma-plugin-datastruct was resolved to 0.2.0, which depends on
#14 4824.4             isodoc was resolved to 2.0.5.3, which depends on
#14 4824.4               emf2svg
#14 ERROR: process "/bin/sh -c cd /setup &&   bundle install --no-cache --redownload &&   rm -rf /usr/local/bundle/cache" did not complete successfully: exit code: 5
------
 > [stage-0  9/10] RUN --mount=type=secret,id=bundle_rubygems__pkg__github__com,dst=/usr/local/bundle/config   cd /setup &&   bundle install --no-cache --redownload &&   rm -rf /usr/local/bundle/cache:
#14 4824.4 An error occurred while installing emf2svg (1.0.0), and Bundler cannot continue.
#14 4824.4 
#14 4824.4 In Gemfile:
#14 4824.4   metanorma-cli was resolved to 1.5.11, which depends on
#14 4824.4     metanorma-bipm was resolved to 2.0.5, which depends on
#14 4824.4       metanorma-generic was resolved to 2.0.3, which depends on
#14 4824.4         metanorma-standoc was resolved to 2.0.4, which depends on
#14 4824.4           metanorma-plugin-datastruct was resolved to 0.2.0, which depends on
#14 4824.4             isodoc was resolved to 2.0.5.3, which depends on
#14 4824.4               emf2svg
```

@CAMOBAP we probably should separate the build job for linux/amd64 and linux/arm64 so that they can pass/fail independently.

**Comment by maxirmx** [comment]
```
#14 4824.4 /usr/local/bundle/gems/mini_portile2-2.6.1/lib/mini_portile2/mini_portile.rb:418:in
#14 4824.4 `spawn': No such file or directory - cmake (Errno::ENOENT)
```
It looks like it does not have cmake installed

**Comment by CAMOBAP** [comment]
> @CAMOBAP we probably should separate the build job for linux/amd64 and linux/arm64 so that they can pass/fail independently.

Yep, will do

> ```
> #14 4824.4 /usr/local/bundle/gems/mini_portile2-2.6.1/lib/mini_portile2/mini_portile.rb:418:in
> #14 4824.4 `spawn': No such file or directory - cmake (Errno::ENOENT)
> ```
> 
> It looks like it does not have cmake installed

Probably I will avoid this with https://github.com/metanorma/emf2svg-ruby/issues/9

**Comment by maxirmx** [comment]
> ```
> #14 4824.4 /usr/local/bundle/gems/mini_portile2-2.6.1/lib/mini_portile2/mini_portile.rb:418:in
> #14 4824.4 `spawn': No such file or directory - cmake (Errno::ENOENT)
> ```
> 
> It looks like it does not have cmake installed

I am checking if adding cmake helps

**Comment by CAMOBAP** [comment]
arm64 containers will be fixed after https://github.com/metanorma/emf2svg-ruby/issues/9 release

**Comment by ronaldtse** [comment]
Thank you @CAMOBAP !

**Pull request merged**
