### PR TITLE
#39 upgrare ruby version to 2.6

### PR DESCRIPTION
**Pull request by CAMOBAP795**
- #39

### CODE REVIEW

**Comment by ronaldtse** [comment]
@camobap795 can we update the Travis tests to test more comprehensively? For example, it should really run the sample document repos, include mn-ogc-documents , mn-itu-docs, etc. Thanks!

**Comment by ronaldtse** [comment]
@CAMOBAP795 this PR will be pending on the added tests. Thanks!

**Comment by ronaldtse** [comment]
ping @CAMOBAP795 can you please help add the tests on the resulting docker image? Thanks.

**Comment by ronaldtse** [comment]
ping @CAMOBAP795 can you please help add the tests on the resulting docker image? Thanks.

**Comment by CAMOBAP795** [comment]
@ronaldtse to add tests I need to merge PR which are linked to #39 first

**Comment by ronaldtse** [comment]
OK, merged.

**Comment by CAMOBAP795** [comment]
@ronaldtse it's ok to merge this one but I asked about :
 - https://github.com/metanorma/mn-samples-iec/pull/2
 - https://github.com/metanorma/csd-public-documents/pull/7

too

**Comment by ronaldtse** [comment]
@CAMOBAP795 all merged.

**Pull request merged**
